tap "buo/cask-upgrade"
tap "homebrew/dupes"
tap "homebrew/completions"
tap "homebrew/science"
tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/python"
tap "homebrew/bundle"
tap "homebrew/services"
tap "github/bootstrap"
tap "caskroom/drivers"
tap "caskroom/versions"
tap "caskroom/cask"
cask "java"
cask "xquartz"
brew "apache-arrow"
brew "apache-spark"
brew "autoconf"
brew "bash-completion"
brew "bats"
brew "boost-build"
brew "brew-cask-completion"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "libffi"
brew "pcre"
brew "pixman"
brew "cereal"
brew "cmake"
brew "cowsay"
brew "diff-so-fancy"
brew "flatbuffers"
brew "openssl"
brew "libevent"
brew "xz"
brew "folly"
brew "fzf"
brew "gmp"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "git", args: ["with-gettext", "with-pcre2"]
brew "git-imerge"
brew "git-lfs"
brew "go"
brew "gobject-introspection"
brew "gsl"
brew "hadoop"
brew "harfbuzz"
brew "hive"
brew "hub", args: ["HEAD"]
brew "oniguruma"
brew "jq"
brew "kubernetes-cli"
brew "launch_socket_server", restart_service: true
brew "launchdns", restart_service: true
brew "libyaml"
brew "llvm"
brew "mackup"
brew "makedepend"
brew "mas"
brew "maven"
brew "mysql", args: ["with-debug", "with-embedded", "with-local-infile", "with-test"], restart_service: true
brew "nginx", restart_service: true
brew "node"
brew "openblas"
brew "openssl@1.1"
brew "presto"
brew "protobuf"
brew "readline"
brew "pyenv"
brew "pyenv-virtualenv"
brew "sqlite", args: ["with-dbstat", "with-docs", "with-fts", "with-functions", "with-icu4c", "with-json1"]
brew "python3", args: ["with-sphinx-doc"]
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "scons"
brew "shared-mime-info"
brew "tmux"
brew "tree"
cask "atom"
cask "banktivity"
cask "bartender"
cask "cloak"
cask "dash"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-hangouts"
cask "gpgtools"
cask "istat-menus"
cask "keepingyouawake"
cask "keybase"
cask "little-snitch"
cask "marked"
cask "screenhero"
cask "slack"
cask "sublime-text"
cask "torbrowser"
cask "tresorit"
cask "viscosity"
cask "whatsapp"
cask "wireshark"
cask "zoomus"
mas "1Password", id: 443987910
mas "Electron APIs", id: 1119345146
mas "GarageBand", id: 682658836
mas "GIFBrewery", id: 435989461
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Marked 2", id: 890031187
mas "Mousepose", id: 405904955
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "ScreenFlow", id: 917790450
mas "Skitch", id: 425955336
mas "The Unarchiver", id: 425424353
