#!/bin/bash
#/ Usage: script/bootstrap
#/
#/ Install the Python package(s) needed for this repo. Assumes pyenv and pipenv
#/ are available.
#/

set -e

# if help requested, print the comments at the top of the file
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "help" ]; then
  grep "^#/" < "$0" | cut -c4-
  exit 0
fi

cd "$(dirname "$0")/.."

if ! which pyenv >/dev/null; then
    echo "pyenv not installed; have you run script/setup?"
    exit 1
fi
if ! pyenv which pipenv >/dev/null 2>&1; then
    echo "pipenv not available; have you run script/setup?"
    exit 1
fi

echo "==> Installing this repo's Python dependencies"
pipenv install

echo "==> Boostrapping done"
