#!/bin/bash
#/ Usage: script/bootstrap
#/
#/ This:
#/   - ...
#/

set -e

# if help requested, print the comments at the top of the file
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "help" ]; then
  grep "^#/" < "$0" | cut -c4-
  exit 0
fi

cd "$(dirname "$0")/.."

source .env

# TODO: basic new machine setup

# echo "==> Installing global Python packages"
# TODO: read location of global python requirements from mackup config
# pip install --upgrade --requirement "$GLOBAL_PYTHON_REQUIREMENTS"

echo "==> Installing this repo's Python dependencies"
pipenv install

# workarounds for current limitations in mackup
# TODO...

echo "==> Boostrapping done"
