#!/bin/bash
#/ Usage: script/mackup
#/
#/ Forward commands to mackup
#/

set -e

# if help requested, print the comments at the top of the file
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "help" ]; then
  pipenv run mackup --help
  exit 0
fi

cd "$(dirname "$0")/.."

pipenv run mackup $@
