#!/bin/bash
#/ Usage: script/update-global-packages
#/
#/ Update All The Things, i.e.
#/   - Homebrew packages (including Cask-installed apps)
#/   - global Python packages
#/

# if help requested, print the comments at the top of the file
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "help" ]; then
  grep "^#/" < "$0" | cut -c4-
  exit 0
fi


cd "$(dirname "$0")/.."

source .env

echo "==> Updating Homebrew packages..."
brew update && brew upgrade && brew cleanup


echo "==> Updating Homebrew Cask-installed packages (and writing updated Brewfile)..."
brew cu --all --yes --cleanup
# TODO: read location of global brewfile from mackup config
# brew bundle dump --force --file="$GLOBAL_BREWFILE"

echo "==> Updating global Python packages..."
# TODO: read location of global python requirements from mackup config
# pip install --upgrade --requirement "$GLOBAL_PYTHON_REQUIREMENTS"
