tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/completions"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/python"
tap "homebrew/science"
tap "homebrew/services"
tap "homebrew/versions"
brew "autoconf"
brew "bash-completion"
brew "brew-cask-completion"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "libffi"
brew "pcre"
brew "pixman"
brew "cairo"
brew "cmake"
brew "diff-so-fancy"
brew "openssl"
brew "libevent"
brew "xz"
brew "folly", link: false
brew "fzf"
brew "gmp"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "git"
brew "git-imerge"
brew "git-lfs"
brew "go"
brew "gsl"
brew "harfbuzz"
brew "hub"
brew "jpeg"
brew "oniguruma"
brew "jq"
brew "kubernetes-cli"
brew "llvm"
brew "mas"
brew "pkg-config"
brew "readline"
brew "sqlite", args: ["with-fts", "with-functions", "with-json1"]
brew "protobuf"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "scons"
brew "tmux"
brew "tree"
cask "amethyst"
cask "appcleaner"
cask "audirvana-plus"
cask "bartender"
cask "docker"
cask "encryptme"
cask "firefox"
cask "google-chrome"
cask "google-hangouts"
cask "gpgtools"
cask "istat-menus"
cask "keepingyouawake"
cask "keybase"
cask "little-snitch"
cask "minikube"
cask "omnigraffle"
cask "sonos"
cask "sublime-text"
cask "tidal"
cask "torbrowser"
cask "tresorit"
cask "viscosity"
cask "wireshark"
cask "xquartz"
mas "1Password", id: 443987910
mas "Electron APIs", id: 1119345146
mas "GarageBand", id: 682658836
mas "GhosteryLite", id: 1436953057
mas "GIFBrewery", id: 435989461
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Marked 2", id: 890031187
mas "Mousepose", id: 405904955
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "ScreenFlow", id: 917790450
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
